name: HelloWorld

on: push
    
    

env:
  FILE_NAME: hello-server

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Build for Linux
        run: go build ${{ env.FILE_NAME }}.go

      
      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifact
          

      
      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      
      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: ${{ env.FILE_NAME }}.exe
